language: objective-c
osx_image: xcode8.2
env:
  global:
    secure: XGW7EX6Hk84CxfMO6UPtKnWU0qOywLrdd8EwdK71pN7MSWJzzD/hScW4xiMGQPOtrY8+1tBi61+rouHJNCSHymcQ953a1FNUfVPfgpb0cCMqAkseuTUAJ4KtkIgPYLj3uSE3a06XriPs0ZO0TptMyoFBlPhdQjQTfOgr5sJ7Eg58B6b88z8J5kYdyoGL+WmHgYruI/CfbjQFswXRN8P3mEEkqskcE+fOhtUHNY2bD+STUbEPkBcgEeR/tvRvaFNdAm0nk+iZgOOtyQCmqO+OjvMqlW0+cjJG598bNHjRR+0a1hRpEsIDEkR3bTQ4JZZGGnqSDPZ9sMDd8oDNlDUJmCpQqUcLyDaIYmUVMWABsl4ubhVquWhl9hoeVP26Jf7IqMke3crFj51tMHkv+uiRjJyEx4dcUhUbFGmaLooV6zIW4y25kMshTqdeSa9yASpC5KjW9NPdV1Qer6dgUFYg/yFY2W/cPKTEfy4O4blrP6pQYUSC2AOiHum4F+GPgcnURXVglu7uONiKsiw8jpDCjGO0kPgBaVdQhPdWdXWLR79q++KSbdB3+jPi2IqQC+rclzujTVq2wJrwNt74U9rBLsfnkH7EnJdFaCyInsEy0TSYp/2xa0Jfz8qbqv4st8zhDNqUj/mlVtEkF/L9DWdydRD6QEhseVGWF585WLcBZy4=
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPad 2"
      SCHEME="PlotModel iOS"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)"
      SCHEME="PlotModel iOS"
    - DESTINATION="platform=OS X"
      SCHEME="PlotModel macOS"

before_script:
- git config --global user.name "Travis CI"
- git config --global user.email "travis@ci.com"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- if [ -f ./Cartfile ]; then carthage update --no-use-binaries; fi;

script: travis_retry xcodebuild test
  -project PlotModel.xcodeproj
  -scheme "${SCHEME}"
  -destination "${DESTINATION}"
  TOOLCHAINS=swift

after_success:
- bash <(curl -s https://codecov.io/bash)
- gem install jazzy
- git clone https://${GH_TOKEN}@github.com/dn-m/dn-m.github.io.git -b nuke
- jazzy
- cd dn-m.github.io
- git add .
- git commit -m "Update docs"
- git push origin nuke
